services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: wallflower
      POSTGRES_PASSWORD: wallflower
      POSTGRES_DB: wallflower
    ports:
      - "5432:5432"
    volumes:
      - wallflower_db_data:/var/lib/postgresql/data

volumes:
  wallflower_db_data:
